# .travis.yml
language: go
go: '1.12.x'

git:
  depth: 1
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
services:
  - docker
script:
  - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.21 golangci-lint run -v -e TIMEOUT=10m
  - go mod vendor && go install -mod vendor
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux