# .travis.yml
language: go
go: '1.12.x'

env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux