apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: submariner-k8s-broker-client:client
  namespace: submariner-k8s-broker
rules:
  - apiGroups: ["submariner.io"]
    resources: ["clusters", "endpoints"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: submariner-k8s-broker-client:client
  namespace: submariner-k8s-broker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: submariner-k8s-broker-client:client
subjects:
  - kind: ServiceAccount
    name: submariner-k8s-broker-client
    namespace: submariner-k8s-broker
