apiVersion: v1
baseDomain: {{.DNSDomain}}
compute:
  - hyperthreading: Enabled
    name: worker
    platform: {}
    replicas: {{.NumWorkers}}
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: {{.NumMasters}}
metadata:
  creationTimestamp: null
  name: {{(.ClusterName)}}
networking:
  clusterNetwork:
    - cidr: {{.PodCidr}}
      hostPrefix: 23
  machineCIDR: {{.VpcCidr}}
  networkType: OpenShiftSDN
  serviceNetwork:
    - {{ .SvcCidr }}
platform:
  {{- if (eq .Platform.Name "aws")}}
  aws:
    region: {{.Platform.Region}}
  {{- end}}
  {{- if (eq .Platform.Name "openstack")}}
  openstack:
    cloud: openstack
    computeFlavor: "{{.Platform.ComputeFlavor}}"
    externalNetwork: "{{.Platform.ExternalNetwork}}"
    lbFloatingIP: "{{.Platform.LbFloatingIP}}"
    region: "{{.Platform.Region}}"
    trunkSupport: "1"
    octaviaSupport: "0"
  {{- end}}
pullSecret: '{{.PullSecret}}'
sshKey: |
  {{.SSHKey}}