apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: openshift-submariner
  name: openshift-submariner
  annotations:
    olm.providedAPIs: Cluster.v1.submariner.io,Endpoint.v1.submariner.io,Submariner.v1alpha1.submariner.io
spec:
  targetNamespaces:
    - openshift-submariner
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: submariner
  namespace: openshift-submariner
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: submariner
  source: submariner-operators
  sourceNamespace: openshift-marketplace
  startingCSV: submariner-operator.v{{.OperatorTag}}